=begin comment
===========================================================
DO NOT MODIFY - START
===========================================================

 Any changes to this file will not persist while grading. 
 Feel free to change it for debugging

=end comment
=cut

#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");
entry("get_policy_result");
entry("read_runtime");
entry("waitnohang");
# entry("result");
entry("myticks");
entry("myvruntimes");
entry("myminimumvruntimes");
=begin comment
===========================================================
DO NOT MODIFY - END
===========================================================

=end comment
=cut