"""
debug_check.py  --  Evaluation harness for the LinearRegressionTree lab.

This script is given to students as a black-box correctness checker.
It does NOT contain any direct logical checks of the tree internals.

All test cases were pre-generated by setup_debug.py using the reference
implementation.  For each case, this script:

  1. Loads the held-out (X_test, y_test) and reference predictions.
  2. Fits YOUR tree on the stored (X_train, y_train).
  3. Evaluates three independent criteria:
       (a) Prediction closeness  -- mean absolute deviation from reference
       (b) R^2 score             -- coefficient of determination on test set, higher is better. max achievable is 1.
       (c) MSE                   -- mean squared error on test set

A case PASSES only when ALL three criteria are satisfied.

Run:
    python debug_check.py
"""

import os
import sys
import json
import traceback
import numpy as np
from tree import LinearRegressionTree

TESTS_DIR = "tests"

# -----------------------------------------------------------------------
# Metrics
# -----------------------------------------------------------------------

def r2_score(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    return (1.0 - ss_res / ss_tot) if ss_tot > 0 else 0.0


def mse_score(y_true, y_pred):
    return float(np.mean((y_true - y_pred) ** 2))


# -----------------------------------------------------------------------
# Load helpers
# -----------------------------------------------------------------------

def load_case(case_dir):
    X_train    = np.load(os.path.join(case_dir, "X_train.npy"))
    y_train    = np.load(os.path.join(case_dir, "y_train.npy"))
    X_test     = np.load(os.path.join(case_dir, "X_test.npy"))
    y_test     = np.load(os.path.join(case_dir, "y_test.npy"))
    y_pred_ref = np.load(os.path.join(case_dir, "y_pred_ref.npy"))
    with open(os.path.join(case_dir, "meta.json")) as f:
        meta = json.load(f)
    return X_train, y_train, X_test, y_test, y_pred_ref, meta


# -----------------------------------------------------------------------
# Evaluate a single case
# -----------------------------------------------------------------------

def run_case(case_dir):
    """
    Load one test case, fit the student's tree, and evaluate.

    Returns
    -------
    passed : bool
    sub_results : list of (sub_name, passed, detail_str)
    """
    X_train, y_train, X_test, y_test, y_pred_ref, meta = load_case(case_dir)

    max_depth = meta["max_depth"]   # None stored as null → Python None
    lam       = float(meta["lam"])

    # --- fit student's tree ---
    tree = LinearRegressionTree(max_depth=max_depth, lam=lam)
    tree.fit(X_train, y_train)

    # --- predict ---
    y_pred = tree.predict(X_test)
    y_pred = np.asarray(y_pred, dtype=float).ravel()

    # -----------------------------------------------------------------
    # Sub-check (a): mean absolute deviation from reference predictions
    # -----------------------------------------------------------------
    mad        = float(np.mean(np.abs(y_pred - y_pred_ref)))
    mad_thr    = float(meta["mad_threshold"])
    a_pass     = mad <= mad_thr
    a_detail   = f"MAD={mad:.4f}  threshold={mad_thr:.4f}"

    # -----------------------------------------------------------------
    # Sub-check (b): R^2 on test set
    # -----------------------------------------------------------------
    r2      = r2_score(y_test.ravel(), y_pred)
    r2_thr  = float(meta["r2_threshold"])
    b_pass  = r2 >= r2_thr
    b_detail = f"R2={r2:.4f}  threshold={r2_thr:.4f}"

    # -----------------------------------------------------------------
    # Sub-check (c): MSE on test set
    # -----------------------------------------------------------------
    mse      = mse_score(y_test.ravel(), y_pred)
    mse_thr  = float(meta["mse_threshold"])
    c_pass   = mse <= mse_thr
    c_detail = f"MSE={mse:.4f}  threshold={mse_thr:.4f}"

    sub_results = [
        ("Prediction closeness (MAD)", a_pass, a_detail),
        ("R^2 score on test set",      b_pass, b_detail),
        ("MSE on test set",            c_pass, c_detail),
    ]

    passed = a_pass and b_pass and c_pass
    return passed, sub_results


# -----------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------

if __name__ == "__main__":
    # Discover test cases
    if not os.path.isdir(TESTS_DIR):
        print(f"[ERROR] Test directory '{TESTS_DIR}/' not found.")
        print("        Make sure you are running from the correct directory.")
        sys.exit(1)

    case_dirs = sorted(
        d for d in (
            os.path.join(TESTS_DIR, e) for e in os.listdir(TESTS_DIR)
        )
        if os.path.isdir(d) and os.path.exists(os.path.join(d, "meta.json"))
    )

    if not case_dirs:
        print(f"[ERROR] No test cases found in '{TESTS_DIR}/'.")
        sys.exit(1)

    total   = len(case_dirs)
    n_pass  = 0
    n_fail  = 0

    print("=" * 68)
    print("  LinearRegressionTree  —  Debug Check")
    print("=" * 68)

    for case_dir in case_dirs:
        with open(os.path.join(case_dir, "meta.json")) as f:
            meta = json.load(f)

        name = meta["name"]
        desc = meta["desc"]

        print(f"\n  Case {meta['case_id']}  |  {name}")
        print(f"           {desc}")
        print(f"           max_depth={meta['max_depth']}  lam={meta['lam']}")
        print(f"           (reference R2={meta['r2_ref']:.4f}  "
              f"MSE={meta['mse_ref']:.4f})")
        print()

        try:
            passed, sub_results = run_case(case_dir)
        except Exception as e:
            print(f"    [ERROR] Exception during evaluation:")
            traceback.print_exc()
            passed = False
            sub_results = []

        for sub_name, sub_pass, detail in sub_results:
            status = "PASS" if sub_pass else "FAIL"
            print(f"    [{status}]  {sub_name:<35}  {detail}")

        verdict = "PASS" if passed else "FAIL"
        print(f"\n    => Case result:  {verdict}")
        print("  " + "-" * 65)

        if passed:
            n_pass += 1
        else:
            n_fail += 1

    # Final summary
    print()
    print("=" * 68)
    print(f"  SUMMARY:  {n_pass}/{total} cases passed,  {n_fail}/{total} cases failed")
    print("=" * 68)

    sys.exit(0 if n_fail == 0 else 1)
